type TeamSeason {
  _id: String!
  team: Team!
  principal: String!
  points: Int!
  position: Int!
  races: [Race]
  car: Car!
  drivers(filter: DriverFilter, sort: DriverSort, limit: Int): [Driver]!
  season: Season
}