type Country {
  _id: String!
  drivers(filter: DriverFilter, sort: DriverSort, limit: Int): [Driver]!
  name: String!
  factories: [Factory]!
  flag: String
  circuits(filter: CircuitFilter, sort: CircuitSort, limit: Int): [Circuit]!
}
