type Query {
  drivers(filter: DriverFilter): [Driver]
  driver(id: String): Driver
  driverSeasons: [DriverSeason]
  teams(name: String): [Team]
  teamSeasons: [TeamSeason]
  countries(name: String): [Country]
  factories: [Factory]
  circuits(name: String, country: String): [Circuit]
  cars: [Car]
  seasons(year: Int): [Season]
  races(name: String): [Race]
}
