type Query {
  drivers: [Driver]
  driver(id: String): Driver
  driverSeasons: [DriverSeason]
  teams: [Team]
  teamSeasons: [TeamSeason]
  countries: [Country]
  factories: [Factory]
  circuits: [Circuit]
  cars: [Car]
  seasons: [Season]
  races: [Race]
}
