type Query {
  drivers(filter: DriverFilter, sort: DriverSort, limit: Int): [Driver]
  driver(id: String): Driver
  driverSeasons: [DriverSeason]
  teams(filter: TeamFilter, sort: TeamSort, limit: Int): [Team]
  teamSeasons: [TeamSeason]
  countries(filter: CountryFilter, sort: CountrySort, limit: Int): [Country]
  factories: [Factory]
  circuits(filter: CircuitFilter, sort: CircuitSort, limit: Int): [Circuit]
  cars(filter: CarFilter, sort: CarSort, limit: Int): [Car]
  seasons(filter: SeasonFilter, sort: SeasonSort, limit: Int): [Season]
  races(filter: RaceFilter, sort: RaceSort, limit: Int): [Race]
}
