type Driver {
  firstname: String!
  lastname: String!
  height(unit: LengthUnit = METER): Float!
  birthday: String!
  country: Country
  team: Team
  car: Car
  points: Int!
  position: Int!
  career: Career
  photo: String
}
