type Driver {
  _id: String
  firstname: String!
  lastname: String!
  height(unit: LengthUnit = METER): Float!
  birthday: Date!
  country: Country
  team: Team
  car: Car
  points: Int!
  position: Int!
  career: Career
  picture: String
  number: Int!
}
