type Driver {
  _id: String!
  country: Country!
  firstname: String!
  lastname: String!
  height(unit: LengthUnit = METER): Float!
  birthday: Date!
  picture: String
  links: Links
  driverSeasons: [DriverSeason]
}
