type DriverSeason {
  _id: String!
  number: Int!
  points: Int!
  position: Int!
  teams(filter: TeamFilter, sort: TeamSort, limit: Int): [Team]
  cars: [Car]
  driver: Driver!
  races: [Race]
  season: Season
}
