type Race {
  _id: String!
  season: Season!
  circuit: Circuit!
  laps: Int!
  qualifying(
    filter: QualifyingFilter
    sort: QualifyingSort
    limit: Int
  ): [Qualifying]
  fastestLaps: [FastestLap]
  results: [Result]
  name: String!
}
